/**
 * Anvil Test Setup
 * Provides test utilities for interacting with local Anvil chain
 */
import {
  createTestClient,
  createPublicClient,
  createWalletClient,
  http,
  parseEther,
  type Address,
  type Hex,
  type PublicClient,
  type TestClient,
  type WalletClient,
  type Chain,
  type Transport,
} from 'viem';
import { foundry } from 'viem/chains';
import { privateKeyToAccount, type PrivateKeyAccount } from 'viem/accounts';

// Anvil's default RPC URL
export const ANVIL_RPC_URL = 'http://127.0.0.1:8545';

// Anvil's deterministic test accounts (DO NOT use in production!)
// These are the default accounts generated by Anvil with known private keys
export const ANVIL_PRIVATE_KEYS = {
  account0: '0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80',
  account1: '0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d',
  account2: '0x5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a',
  account3: '0x7c852118294e51e653712a81e05800f419141751be58f605c371e15141b007a6',
  account4: '0x47e179ec197488593b187f80a00eb0da91f1b9d0b13f8733639f19c30a34926a',
} as const;

// Pre-configured test accounts
export const TEST_ACCOUNTS = {
  deployer: privateKeyToAccount(ANVIL_PRIVATE_KEYS.account0),
  user1: privateKeyToAccount(ANVIL_PRIVATE_KEYS.account1),
  user2: privateKeyToAccount(ANVIL_PRIVATE_KEYS.account2),
  user3: privateKeyToAccount(ANVIL_PRIVATE_KEYS.account3),
  user4: privateKeyToAccount(ANVIL_PRIVATE_KEYS.account4),
} as const;

// Test Client - for test actions (mine, reset, impersonate, etc.)
export const createAnvilTestClient = (): TestClient<'anvil', Transport, Chain> =>
  createTestClient({
    chain: foundry,
    mode: 'anvil',
    transport: http(ANVIL_RPC_URL),
  });

// Public Client - for reading blockchain state
export const createAnvilPublicClient = (): PublicClient<Transport, Chain> =>
  createPublicClient({
    chain: foundry,
    transport: http(ANVIL_RPC_URL),
  });

// Wallet Client factory - for sending transactions
export const createAnvilWalletClient = (
  account: PrivateKeyAccount
): WalletClient<Transport, Chain, PrivateKeyAccount> =>
  createWalletClient({
    account,
    chain: foundry,
    transport: http(ANVIL_RPC_URL),
  });

// Singleton instances for convenience
let testClientInstance: TestClient<'anvil', Transport, Chain> | null = null;
let publicClientInstance: PublicClient<Transport, Chain> | null = null;

export const getTestClient = (): TestClient<'anvil', Transport, Chain> => {
  if (!testClientInstance) {
    testClientInstance = createAnvilTestClient();
  }
  return testClientInstance;
};

export const getPublicClient = (): PublicClient<Transport, Chain> => {
  if (!publicClientInstance) {
    publicClientInstance = createAnvilPublicClient();
  }
  return publicClientInstance;
};

// Reset singleton instances (useful for test cleanup)
export const resetClients = (): void => {
  testClientInstance = null;
  publicClientInstance = null;
};

/**
 * Mine a specified number of blocks
 */
export const mineBlocks = async (blocks: number): Promise<void> => {
  const testClient = getTestClient();
  await testClient.mine({ blocks });
};

/**
 * Mine a single block
 */
export const mineBlock = async (): Promise<void> => {
  await mineBlocks(1);
};

/**
 * Set the balance of an address
 */
export const setBalance = async (
  address: Address,
  value: bigint = parseEther('100')
): Promise<void> => {
  const testClient = getTestClient();
  await testClient.setBalance({ address, value });
};

/**
 * Impersonate an account (allows sending transactions from any address)
 */
export const impersonateAccount = async (address: Address): Promise<void> => {
  const testClient = getTestClient();
  await testClient.impersonateAccount({ address });
};

/**
 * Stop impersonating an account
 */
export const stopImpersonating = async (address: Address): Promise<void> => {
  const testClient = getTestClient();
  await testClient.stopImpersonatingAccount({ address });
};

/**
 * Create a snapshot of the current chain state
 */
export const snapshot = async (): Promise<Hex> => {
  const testClient = getTestClient();
  return testClient.snapshot();
};

/**
 * Revert to a previous snapshot
 */
export const revert = async (id: Hex): Promise<void> => {
  const testClient = getTestClient();
  await testClient.revert({ id });
};

/**
 * Reset the chain to its initial state
 */
export const resetChain = async (): Promise<void> => {
  const testClient = getTestClient();
  await testClient.reset();
};

/**
 * Set the next block's timestamp
 */
export const setNextBlockTimestamp = async (timestamp: bigint): Promise<void> => {
  const testClient = getTestClient();
  await testClient.setNextBlockTimestamp({ timestamp });
};

/**
 * Increase time by a specified number of seconds and mine a block
 */
export const increaseTime = async (seconds: number): Promise<void> => {
  const testClient = getTestClient();
  await testClient.increaseTime({ seconds });
  await mineBlock();
};

/**
 * Helper: Execute a function within a snapshot context
 * Automatically reverts to the snapshot after execution
 */
export const withSnapshot = async <T>(fn: () => Promise<T>): Promise<T> => {
  const id = await snapshot();
  try {
    return await fn();
  } finally {
    await revert(id);
  }
};

/**
 * Wait for a transaction to be mined and return the receipt
 */
export const waitForTransaction = async (hash: Hex) => {
  const publicClient = getPublicClient();
  return publicClient.waitForTransactionReceipt({ hash });
};

/**
 * Get the current block number
 */
export const getBlockNumber = async (): Promise<bigint> => {
  const publicClient = getPublicClient();
  return publicClient.getBlockNumber();
};

